name: Tool Version Deprecation Check
description: 'Checks if the tool version is deprecated'

inputs:
  github-token:
    description: 'GitHub Token'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'
